server:
  servlet:
    context-path: /api/v1
  port: 8080
management:
  endpoints:
    web:
      base-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://advert-rds.cjdz8mocsswq.us-east-1.rds.amazonaws.com:3306/db_advert?serverTimezone=UTC&useSSL=false

advertise:
  host: http://advertise-system-env.eba-yp38yrgb.us-east-1.elasticbeanstalk.com/api/v1

aws:
  accessKey: AWS_ACCESS_KEY
  secretAccess: AWS_SECRET_ACCESS
  sqs:
    advert-interested-email-queue: https://sqs.us-east-1.amazonaws.com/909678944137/pos_puc_advert_interested_email_queue
  s3:
    advert-images-bucket: pos-puc-advert-images-bucket